OCR_DATA_PATH = r'C:\Users\shald\Downloads\ocr_data.csv'
ROOT_DATA_PATH = r'C:\Users\shald\Downloads\KAIST_all\KAIST\English'
KERAS_OUTPUT_CSV_PATH = r'C:\Users\shald\open_source\repositories\output\keras_ocr.csv'
TESSERACT_OUTPUT_CSV_PATH = r'C:\Users\shald\open_source\repositories\output\tesseract_ocr.csv'
TESSERACT_MODEL_PATH = r'C:\Program Files\Tesseract-OCR\tesseract.exe'